default:
  properties:
    proxy.enabled: false
    proxy.ip: 127.0.0.1
    proxy.port: 9000
    timings.implicitTimeout: 10
    allure.report: true
    allure.create.enviroment: true
  contexts: [chrome,locator,dev]
