default:
  properties:
    proxy.enabled: false
    proxy.ip: 127.0.0.1
    proxy.port: 9000
    bobcat.report.path: ./target/report
    bobcat.report.reporters: html,json,simple,stdout
  contexts: [appium]