default:
  properties:
    proxy.enabled: false
    proxy.ip: 127.0.0.1
    proxy.port: 9000
    page.title.timeout: 30
    allure.report: true
    allure.create.enviroment: true
    timings.implicitTimeout: 10
  contexts: [chrome]
